steps:
  # Paso 1: Construcción de la imagen del contenedor
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME
      - .
      - '-f'
      - ./Dockerfile
    id: Build

  # Paso 2: Empujar la imagen del contenedor a Container Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME
    id: Push

  # Paso 3: Desplegar el servicio en Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    args:
      - gcloud
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy

options:
  logging: CLOUD_LOGGING_ONLY
